### ISSUE TITLE
Real World Performance

### ISSUE THREAD

**Issue by RoyiAvital** [Khanattila/KNLMeansCL#16]
Hello,
How many Frames Per Second can it yield on modern Intel CPU (Intel OpenCL Driver)?
How about on modern GPU (Not the high end models)?

Thank You.

**Comment by Khanattila** [comment]
See Benchmark at the end of the file: https://github.com/Khanattila/KNLMeansCL/blob/master/DOC.md
CPU is much slower, ~5/6 FPS maybe.

**Comment by RoyiAvital** [comment]
Hi,
Even with AVX on Haswell / Broadwell / Skylake?

I'm talking about 1080p frames.

Thank You.

**Comment by Khanattila** [comment]
Haswell / Broadwell / Skylake and 1080p?  ~1 fps maybe.
On CPU use a smaller 'd' and 'a' is recommended.
However, the use of a GPU is always recommended.

**Comment by RoyiAvital** [comment]
@Khanattila, Is there a way to contact you on email?

Thank You.

**Comment by Khanattila** [comment]
What's the matter?

**Comment by RoyiAvital** [comment]
Hi,
I know someone who wants to have your advising on NLM.

Thank You.

**Comment by RoyiAvital** [comment]
@Khanattila ,
Did you get my last message?

Thank You.

**Comment by Khanattila** [comment]
Tell him to write directly on github.

**Comment by RoyiAvital** [comment]
Hi,
It would be hard, he doesn't have an account and it wouldn't be appropriate.

Please, it is something you'd be happy to hear about.

Thank You.

**Comment by Khanattila** [comment]
https://sites.google.com/site/khanattilasfilters/about

**Comment by RoyiAvital** [comment]
Hi,

By the way, does it work on Floating Point images (Each channel as 32 Bit Float)?

Thank You.

**Comment by Khanattila** [comment]
yes of course

**Comment by RoyiAvital** [comment]
That's interesting.

Could it be adopted into OpenCV which lacks support for Floating Point?

**Comment by Khanattila** [comment]
Some changes should be made to work with OpenCV.
Also there are some licensing issues.

**Comment by RoyiAvital** [comment]
Is there an issue to run it for University Project?

**Comment by Khanattila** [comment]
You can do anything the GPL permits: http://choosealicense.com/licenses/gpl-3.0/.
