### ISSUE TITLE
Incorrect VapourSynth API usage

### ISSUE THREAD

**Issue by dubhater** [Khanattila/KNLMeansCL#17]
Hi.

You're not supposed to free the filter's input nodes in the VapourSynthPluginGetFrame function: https://github.com/Khanattila/KNLMeansCL/blob/fa49bb5e24606232a340cfe12efcd86478d33549/KNLMeansCL/KNLMeansCL.cpp#L1061 Freeing those nodes will lead to a crash when VapourSynthPluginFree frees them again.

(Errors that occur in the getframe function are not necessarily fatal. That is, the application is free to request the same frame again, or a different frame.)

**Comment by Khanattila** [comment]
Hi, then I will remove all of `vsapi->freeNode(d->node); vsapi->freeNode(d->knot);` from VapourSynthPluginGetFrame. One thing settled. Anyway I did so because it was a practice used in other plugins (myrslok) and maybe now it no longer is.
