### ISSUE TITLE
Script error: KNLMeansCL: no compatible opencl platforms available! (OpenCL 1.2 API)

### ISSUE THREAD

**Issue by MapleFadeAway** [Khanattila/KNLMeansCL#20]
It happends after I update win10 14393.
I tried several kinds of opencl.dll but make no sense.
I install the nvdia CUDA 7.5 and then it say "Script error: KNLMeansCL:fatal error! (oclGetDeviceslist)" or "Script error: KNLMeansCL: no compatible opencl platforms available! (OpenCL 1.2 API)" randomly.
(I have tried 0.7.6 0.7.5 0.7.4)

what should I do?

Here are some information:
C:\Users\user\Desktop\oclDeviceQuery\NVIDIA GPU Computing SDK\OpenCL\bin\Win32\Release\oclDeviceQuery.exe Starting...

OpenCL SW Info:

 CL_PLATFORM_NAME:  NVIDIA CUDA
 CL_PLATFORM_VERSION:   OpenCL 1.2 CUDA 8.0.0
 OpenCL SDK Revision:   7027912

OpenCL Device Info:

 1 devices found supporting OpenCL:

---

 Device GeForce GTX 970M

---

  CL_DEVICE_NAME:           GeForce GTX 970M
  CL_DEVICE_VENDOR:             NVIDIA Corporation
  CL_DRIVER_VERSION:            372.54
  CL_DEVICE_VERSION:            OpenCL 1.2 CUDA
  CL_DEVICE_OPENCL_C_VERSION:       OpenCL C 1.2 
  CL_DEVICE_TYPE:           CL_DEVICE_TYPE_GPU
  CL_DEVICE_MAX_COMPUTE_UNITS:      10
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:   3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:    1024 / 1024 / 64 
  CL_DEVICE_MAX_WORK_GROUP_SIZE:    1024
  CL_DEVICE_MAX_CLOCK_FREQUENCY:    1038 MHz
  CL_DEVICE_ADDRESS_BITS:       32
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:     1536 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:        6144 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:   no
  CL_DEVICE_LOCAL_MEM_TYPE:     local
  CL_DEVICE_LOCAL_MEM_SIZE:     48 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:   64 KByte
  CL_DEVICE_QUEUE_PROPERTIES:       CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
  CL_DEVICE_QUEUE_PROPERTIES:       CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:      1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:    256
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:   16
  CL_DEVICE_SINGLE_FP_CONFIG:       denorms INF-quietNaNs round-to-nearest round-to-zero round-to-inf fma 

  CL_DEVICE_IMAGE <dim>         2D_MAX_WIDTH     16384
                    2D_MAX_HEIGHT    16384
                    3D_MAX_WIDTH     4096
                    3D_MAX_HEIGHT    4096
                    3D_MAX_DEPTH     4096

  CL_DEVICE_EXTENSIONS:         cl_khr_global_int32_base_atomics
                    cl_khr_global_int32_extended_atomics
                    cl_khr_local_int32_base_atomics
                    cl_khr_local_int32_extended_atomics
                    cl_khr_fp64
                    cl_khr_byte_addressable_store
                    cl_khr_icd
                    cl_khr_gl_sharing
                    cl_nv_compiler_options
                    cl_nv_device_attribute_query
                    cl_nv_pragma_unroll
                    cl_nv_d3d10_sharing
                    cl_khr_d3d10_sharing
                    cl_nv_d3d11_sharing

  CL_DEVICE_COMPUTE_CAPABILITY_NV:  5.2
  NUMBER OF MULTIPROCESSORS:        10
  NUMBER OF CUDA CORES:         4294967286
  CL_DEVICE_REGISTERS_PER_BLOCK_NV: 65536
  CL_DEVICE_WARP_SIZE_NV:       32
  CL_DEVICE_GPU_OVERLAP_NV:     CL_TRUE
  CL_DEVICE_KERNEL_EXEC_TIMEOUT_NV: CL_TRUE
  CL_DEVICE_INTEGRATED_MEMORY_NV:   CL_FALSE
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>  CHAR 1, SHORT 1, INT 1, LONG 1, FLOAT 1, DOUBLE 1

---

  2D Image Formats Supported (75)

---

  #     Channel Order   Channel Type          

  1     CL_R            CL_FLOAT  
  2     CL_R            CL_HALF_FLOAT  
  3     CL_R            CL_UNORM_INT8  
  4     CL_R            CL_UNORM_INT16  
  5     CL_R            CL_SNORM_INT16  
  6     CL_R            CL_SIGNED_INT8  
  7     CL_R            CL_SIGNED_INT16  
  8     CL_R            CL_SIGNED_INT32  
  9     CL_R            CL_UNSIGNED_INT8  
  10    CL_R            CL_UNSIGNED_INT16  
  11    CL_R            CL_UNSIGNED_INT32  
  12    CL_A            CL_FLOAT  
  13    CL_A            CL_HALF_FLOAT  
  14    CL_A            CL_UNORM_INT8  
  15    CL_A            CL_UNORM_INT16  
  16    CL_A            CL_SNORM_INT16  
  17    CL_A            CL_SIGNED_INT8  
  18    CL_A            CL_SIGNED_INT16  
  19    CL_A            CL_SIGNED_INT32  
  20    CL_A            CL_UNSIGNED_INT8  
  21    CL_A            CL_UNSIGNED_INT16  
  22    CL_A            CL_UNSIGNED_INT32  
  23    CL_RG           CL_FLOAT  
  24    CL_RG           CL_HALF_FLOAT  
  25    CL_RG           CL_UNORM_INT8  
  26    CL_RG           CL_UNORM_INT16  
  27    CL_RG           CL_SNORM_INT16  
  28    CL_RG           CL_SIGNED_INT8  
  29    CL_RG           CL_SIGNED_INT16  
  30    CL_RG           CL_SIGNED_INT32  
  31    CL_RG           CL_UNSIGNED_INT8  
  32    CL_RG           CL_UNSIGNED_INT16  
  33    CL_RG           CL_UNSIGNED_INT32  
  34    CL_RA           CL_FLOAT  
  35    CL_RA           CL_HALF_FLOAT  
  36    CL_RA           CL_UNORM_INT8  
  37    CL_RA           CL_UNORM_INT16  
  38    CL_RA           CL_SNORM_INT16  
  39    CL_RA           CL_SIGNED_INT8  
  40    CL_RA           CL_SIGNED_INT16  
  41    CL_RA           CL_SIGNED_INT32  
  42    CL_RA           CL_UNSIGNED_INT8  
  43    CL_RA           CL_UNSIGNED_INT16  
  44    CL_RA           CL_UNSIGNED_INT32  
  45    CL_RGBA         CL_FLOAT  
  46    CL_RGBA         CL_HALF_FLOAT  
  47    CL_RGBA         CL_UNORM_INT8  
  48    CL_RGBA         CL_UNORM_INT16  
  49    CL_RGBA         CL_SNORM_INT16  
  50    CL_RGBA         CL_SIGNED_INT8  
  51    CL_RGBA         CL_SIGNED_INT16  
  52    CL_RGBA         CL_SIGNED_INT32  
  53    CL_RGBA         CL_UNSIGNED_INT8  
  54    CL_RGBA         CL_UNSIGNED_INT16  
  55    CL_RGBA         CL_UNSIGNED_INT32  
  56    CL_BGRA         CL_UNORM_INT8  
  57    CL_BGRA         CL_SIGNED_INT8  
  58    CL_BGRA         CL_UNSIGNED_INT8  
  59    CL_ARGB         CL_UNORM_INT8  
  60    CL_ARGB         CL_SIGNED_INT8  
  61    CL_ARGB         CL_UNSIGNED_INT8  
  62    CL_INTENSITY    CL_FLOAT  
  63    CL_INTENSITY    CL_HALF_FLOAT  
  64    CL_INTENSITY    CL_UNORM_INT8  
  65    CL_INTENSITY    CL_UNORM_INT16  
  66    CL_INTENSITY    CL_SNORM_INT16  
  67    CL_LUMINANCE    CL_FLOAT  
  68    CL_LUMINANCE    CL_HALF_FLOAT  
  69    CL_LUMINANCE    CL_UNORM_INT8  
  70    CL_LUMINANCE    CL_UNORM_INT16  
  71    CL_LUMINANCE    CL_SNORM_INT16  
  72    CL_BGRA         CL_SNORM_INT8  
  73    CL_BGRA         CL_SNORM_INT16  
  74    CL_ARGB         CL_SNORM_INT8  
  75    CL_ARGB         CL_SNORM_INT16        

---

  3D Image Formats Supported (75)

---

  #     Channel Order   Channel Type          

  1     CL_R            CL_FLOAT  
  2     CL_R            CL_HALF_FLOAT  
  3     CL_R            CL_UNORM_INT8  
  4     CL_R            CL_UNORM_INT16  
  5     CL_R            CL_SNORM_INT16  
  6     CL_R            CL_SIGNED_INT8  
  7     CL_R            CL_SIGNED_INT16  
  8     CL_R            CL_SIGNED_INT32  
  9     CL_R            CL_UNSIGNED_INT8  
  10    CL_R            CL_UNSIGNED_INT16  
  11    CL_R            CL_UNSIGNED_INT32  
  12    CL_A            CL_FLOAT  
  13    CL_A            CL_HALF_FLOAT  
  14    CL_A            CL_UNORM_INT8  
  15    CL_A            CL_UNORM_INT16  
  16    CL_A            CL_SNORM_INT16  
  17    CL_A            CL_SIGNED_INT8  
  18    CL_A            CL_SIGNED_INT16  
  19    CL_A            CL_SIGNED_INT32  
  20    CL_A            CL_UNSIGNED_INT8  
  21    CL_A            CL_UNSIGNED_INT16  
  22    CL_A            CL_UNSIGNED_INT32  
  23    CL_RG           CL_FLOAT  
  24    CL_RG           CL_HALF_FLOAT  
  25    CL_RG           CL_UNORM_INT8  
  26    CL_RG           CL_UNORM_INT16  
  27    CL_RG           CL_SNORM_INT16  
  28    CL_RG           CL_SIGNED_INT8  
  29    CL_RG           CL_SIGNED_INT16  
  30    CL_RG           CL_SIGNED_INT32  
  31    CL_RG           CL_UNSIGNED_INT8  
  32    CL_RG           CL_UNSIGNED_INT16  
  33    CL_RG           CL_UNSIGNED_INT32  
  34    CL_RA           CL_FLOAT  
  35    CL_RA           CL_HALF_FLOAT  
  36    CL_RA           CL_UNORM_INT8  
  37    CL_RA           CL_UNORM_INT16  
  38    CL_RA           CL_SNORM_INT16  
  39    CL_RA           CL_SIGNED_INT8  
  40    CL_RA           CL_SIGNED_INT16  
  41    CL_RA           CL_SIGNED_INT32  
  42    CL_RA           CL_UNSIGNED_INT8  
  43    CL_RA           CL_UNSIGNED_INT16  
  44    CL_RA           CL_UNSIGNED_INT32  
  45    CL_RGBA         CL_FLOAT  
  46    CL_RGBA         CL_HALF_FLOAT  
  47    CL_RGBA         CL_UNORM_INT8  
  48    CL_RGBA         CL_UNORM_INT16  
  49    CL_RGBA         CL_SNORM_INT16  
  50    CL_RGBA         CL_SIGNED_INT8  
  51    CL_RGBA         CL_SIGNED_INT16  
  52    CL_RGBA         CL_SIGNED_INT32  
  53    CL_RGBA         CL_UNSIGNED_INT8  
  54    CL_RGBA         CL_UNSIGNED_INT16  
  55    CL_RGBA         CL_UNSIGNED_INT32  
  56    CL_BGRA         CL_UNORM_INT8  
  57    CL_BGRA         CL_SIGNED_INT8  
  58    CL_BGRA         CL_UNSIGNED_INT8  
  59    CL_ARGB         CL_UNORM_INT8  
  60    CL_ARGB         CL_SIGNED_INT8  
  61    CL_ARGB         CL_UNSIGNED_INT8  
  62    CL_INTENSITY    CL_FLOAT  
  63    CL_INTENSITY    CL_HALF_FLOAT  
  64    CL_INTENSITY    CL_UNORM_INT8  
  65    CL_INTENSITY    CL_UNORM_INT16  
  66    CL_INTENSITY    CL_SNORM_INT16  
  67    CL_LUMINANCE    CL_FLOAT  
  68    CL_LUMINANCE    CL_HALF_FLOAT  
  69    CL_LUMINANCE    CL_UNORM_INT8  
  70    CL_LUMINANCE    CL_UNORM_INT16  
  71    CL_LUMINANCE    CL_SNORM_INT16  
  72    CL_BGRA         CL_SNORM_INT8  
  73    CL_BGRA         CL_SNORM_INT16  
  74    CL_ARGB         CL_SNORM_INT8  
  75    CL_ARGB         CL_SNORM_INT16        

oclDeviceQuery, Platform Name = NVIDIA CUDA, Platform Version = OpenCL 1.2 CUDA 8.0.0, SDK Revision = 7027912, NumDevs = 1, Device = GeForce GTX 970M

System Info: 

 Local Time/Date = 0:8:34, 8/23/2016
 CPU Arch: 0
 CPU Level: 6
 # of CPU processors: 8
 Windows Build: 9200
 Windows Ver: 6.2 (Windows Vista / Windows 7)

**Comment by Khanattila** [comment]
I have to investigate the problem however, I can advise you to change the driver.
Remove the 372.54 version driver and all the other stuff; then install only the 368.64.

**Comment by Khanattila** [comment]
Or however you please try another older driver.

**Comment by MapleFadeAway** [comment]
Thanks for you reply.

I uninstall the CUDA and try 368.69 362.00 it still said  KNLMeansCL:fatal error! (oclGetDeviceslist)" or "Script error: KNLMeansCL: no compatible opencl platforms available! (OpenCL 1.2 API)" randomly.


This thing had happed when I use WIN10 10586 ,and it work well after I used “sfc /scannow” and "dism /online /cleanup-image /restoreHealth /source:E:\sources\windows /limitaccess" to repair the opencl ,but this time "sfc /scannow" did't find anything need to be repaired.

**Comment by Khanattila** [comment]
Please check again with the last release.

**Comment by MapleFadeAway** [comment]
Thanks,but it said:
Script error: KNLMeansCL: fatal error! (oclUtilsGetPlaformDeviceIDs: OCL_UTILS_UNKNOWN_ERROR)

[oclDeviceQuery.txt](https://github.com/Khanattila/KNLMeansCL/files/450386/oclDeviceQuery.txt)

**Comment by Khanattila** [comment]
Can you post your script?

**Comment by MapleFadeAway** [comment]
`V="E:\[DmzJ][Rental_Magica][VOL.01-12][DVDRip-mkv]\[DmzJ][Rental_Magica][01][DVDRip][x264_mp3].mkv"
FFIndex(V)
FFVideoSource(V,fpsnum=30000,fpsden=1001)
Dither_convert_8_to_16 ()
KNLMeansCL(d=3, a=2, s=4,h=1.0,wmode=1,lsb_inout=true)
#, device_type="GPU",cmode=true
DitherPost (mode=-1)`

After Windows 10 Anniversary Update, I can't use you KNLMeansCL anymore.
Maybe I should use win2008 servers ...
