### ISSUE TITLE
Error with channels = "YUV"

### ISSUE THREAD

**Issue by theChaosCoder** [Khanattila/KNLMeansCL#23]
clip is YUV420P16
knl version 1.1.0

`core.knlm.KNLMeansCL(clip, d=6, a = 8, s = 2, h=3.4, wmode = 3, channels = "YUV")`
Y and UV works but not YUV

> Error on frame 23823 request:
> knlm.KNLMeansCL: fatal error!
> (VapourSynthGetFrame)
> Error on frame 0 request:
> knlm.KNLMeansCL: fatal error!
> (VapourSynthGetFrame)

**Comment by Khanattila** [comment]
It's not a bug. "YUV" requires 4:4:4 sub-ampling.
