### ISSUE TITLE
Have trouble with avisynth

### ISSUE THREAD

**Issue by eorking** [Khanattila/KNLMeansCL#30]
Hi, when I try to use KNL in my avs script, I had some problems.Can you help me?
```
DGSource("E:\Disk1\BDMV\STREAM\00001.dgi")
KNLMeansCL(d=3, a=2, s=4, h=1.5, device_type="GPU")
```
Here Is My Environment:
- AMD 1950X + GTX 1080Ti
- Windows 10 LTSB  64bit
- Avisynth 2.6.0 ST 32bit 
- The plugins folder only contains DGDecodeNV.dll & KNLMeansCL.dll (1.1.1)

I use avspmod to preview the script.
However it turn out to be no response, without any error or warning.

PS: When I change to use VapourSynth. Since dgnv doesn't work on vs, I always use avs...
```
import vapoursynth as vs
core=vs.get_core() 
src=core.lsmas.LWLibavSource(r"E:\Disk1\BDMV\STREAM\00001.m2ts")
src=core.knlm.KNLMeansCL(src, d=3, a=2, s=4, h=1.5, device_type = "GPU")
src.set_output()
```
This vs script works all right.

**Comment by Khanattila** [comment]
Hi eorking, as some users have suggested on the support thread, there is an incompatibility between DGDecodeNV and KNLMeansCL under Avisynth 32bit.  This limitation is believed to be due
to Nvidia driver deficiencies in Windows 10.
