### ISSUE TITLE
blending when set h>20 and d>0

### ISSUE THREAD

**Issue by JasinChen** [Khanattila/KNLMeansCL#33]
core.knlm.KNLmeansCL(video,h=20)

And then I can see the blending in the preview.
It looks like two adjacent  image mixed.
It's more obvious when set 'h' higher.
When set 'd' to 0 the blending disappear.

**Comment by WolframRhodium** [comment]
Isn't it a normal behavior of NLM?
The NLM filter equals simple Gaussian filter in spatial domain and average filter in temporal domain as "h" approaches infinity, and setting "d" to 0 means spatia-only filtering so no temporal blending will occur.

**Comment by Khanattila** [comment]
It's not an issue as @WolframRhodium said.
