### ISSUE TITLE
Nn VapourSynth KNLMeansCL crash (Windows)

### ISSUE THREAD

**Issue by pukanxi** [Khanattila/KNLMeansCL#41]
In the following script will cause vs crash. After removing KNLMeansCL is normal.
GPU:940MX

import vapoursynth as vs
import sys
import havsfunc as haf     
import mvsfunc as mvf      

core = vs.get_core()
core.max_cache_size = 600  #最大占用内存数 

clip = core.lsmas.LWLibavSource(source=r'00005.m2ts', format='yuv420p16')
#lsmash

clip = haf.QTGMC(clip, Preset='Slower', FPSDivisor=2, TFF=True)
#preset为质控

clip = core.knlm.KNLMeansCL(clip, d=1, a=2, s=4, device_type="gpu")

clip.set_output()

**Comment by Khanattila** [comment]
Hi pukanxi, do you have any log files for me? :)

**Comment by pukanxi** [comment]
> Hi pukanxi, do you have any log files for me? :)

Sorry, in VapourSynth Edit  "Check script" The program crashes directly. Did not leave any log

 Operate my computer remotely if your time permits (system is Chinese)

**Comment by pukanxi** [comment]
This problem has been solved perfectly after rewriting the script. It should be my personal problem. Thank you!
