### ISSUE TITLE
KNLMeansCL on Edges/Line Art

### ISSUE THREAD

**Issue by nobananasforyou** [Khanattila/KNLMeansCL#44]
Hello, 

I have a source that benefits from KNLmeansCL's edge/line art repairing ability. It is able to fix the aliasing. I want to know if there is a possibility to apply KNLmeansCL only to edges/line art. I've tested other anti-aliasing filters and they don't seem to have the desired effect. Please let me know if that is possible.

Thank you!

**Comment by Khanattila** [comment]
Hi @nobananasforyou! 

There is no specific mode for what you ask. Anyway, you can use a workaround: you can merge between the original image and the denoised one by using an edge detection mask. 
In this way, you can decide what to preserve from the original image. 

All the best
