### ISSUE TITLE
Unable to use OpenCL accelerator by Radeon RX590

### ISSUE THREAD

**Issue by cby120** [Khanattila/KNLMeansCL#46]
Hello !
I'm having trouble using your product, it would be great pleasure to me if you could offer some suggestions. 
I've made sure that the driver program is the latest official version. Some OpenCL benchmark can be run normally. 
When specifying device type as accelerator, error as 'no compatible opencl platforms available' is returned. When specifying device type as gpu, there's some performance issue. GPU is working at maximum load and CPU is hardly occupied, and the coding speed isn't satisfying.
I wonder if there's efficiency issue using GPU for computing, or could I partly use extra CPU computing resource to speed up the progress?
Thank you very much!

p.s. cpu Ryzen 3700x gpu Radeon RX590

**Comment by Khanattila** [comment]
Hi @cby120! 'accelerator' is reserved for some special dedicated external card (Xeon Phi for example). It doesn't surprise me that it doesn't work: you have to use 'gpu'. 
There should be no efficiency problem, however, the speed obtained depends on the settings of this filter, on the cascade of filters you use and finally if you use an encoder. You should test it one by one to see if there is any problem. 
Moreover, for questions like these, I recommend using the [forum](https://forum.doom9.org/showthread.php?t=171379), it is definitely more suitable and you can discuss with other users.
