### ISSUE TITLE
Unable to use a=0

### ISSUE THREAD

**Issue by End-of-Eternity** [Khanattila/KNLMeansCL#48]
In the documentation it states that,

_**int a [default: 2]**_  
Set the radius of the search window. **a=0 uses 1 pixel,** while a=1 uses 9 pixels and so on. Usually, larger it the better the result of the denoising. Spatial size = (2 * a + 1)^2. 

However when trying to use `a=0`, the following error is returned: `knlm.KNLMeansCL: 'a' must be greater than or equal to 1!`

I'm not 100% if the NL Means algorithm would even work with a single pixel spatial window (maybe for fully temporal filtering?), but in any case, either the documentation should be changed to show that `a=0` is not possible, or the `a>=1` assertion should be modified to be `a>=0`.

**Comment by Khanattila** [comment]
Hi @End-of-Eternity , probably the example in the documentation is not the best possible. Thanks for pointing this out.
