### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by Kuronoe-Ookami** [Khanattila/KNLMeansCL#50]
I am getting the following error:

![image](https://user-images.githubusercontent.com/72235923/106356975-603c6a80-6314-11eb-8aa4-6c2c1cd88523.png)

any suggestions of what might be?
using AVS+ 3.7.0.
AvspMod latest version.

**Comment by Khanattila** [comment]
Have you tried using this fork?
[pinterf](https://github.com/pinterf/KNLMeansCL/releases/tag/v1.1.1e)
Also I invite you to write in the support thread.

**Comment by Kuronoe-Ookami** [comment]
> Have you tried using this fork?
> [pinterf](https://github.com/pinterf/KNLMeansCL/releases/tag/v1.1.1e)
> Also I invite you to write in the support thread.

Great!
worked perfectly.
Thank you friend.
