### ISSUE TITLE
Execute errors like "candidate function not viable"

### ISSUE THREAD

**Issue by brothermechanic** [Khanattila/KNLMeansCL#6]
Hello
This is great filter!
I try to replace mvtools+fft3dfilter with KNLMeansCL
But i have a problem Log-KNLMeansCL.txt  https://bpaste.net/show/e4fe4c1919c1
I have opencl installs for nvidia gpu and intel cpu (i use luxrender and it's work fine with it)
What the problem?
ps
I use script like this
core.knlm.KNLMeansCL(output, d=3, a=2 , s=4 , wmode=1 , h=1.2)

System is gentoo linux amd64

Thank you!

**Comment by 4re** [comment]
Hi

Can you provide the simplest __full__ script that can produce that error (and the output of ```vspipe -i script.py -``` wen you remove knlmeanscl line)? Version for all components (vapoursynth, knlmeanscl, gcc, drivers)? Output for ```eselect opencl list```?

**Comment by brothermechanic** [comment]
this is my test script https://bpaste.net/show/393d241803d8
this is test script from forum https://bpaste.net/show/9e7333eb074f
$ eselect opencl list
Available OpenCL implementations:
  [1]   intel
  [2]   mesa
  [3]   nvidia *
ok http://wstaw.org/m/2015/09/08/plasma-desktoprD4436.png
error http://wstaw.org/m/2015/09/08/plasma-desktopFm4436.png

**Comment by brothermechanic** [comment]
i just check forum http://forum.doom9.org/showthread.php?t=171379&page=20
and test this script
[code] 
import vapoursynth as vs
core = vs.get_core()

clip = core.std.BlankClip(format=vs.YUV444P16)
clip = core.knlm.KNLMeansCL(clip, cmode=True)
clip.set_output()
[/code]
run as 
$ vspipe -p cl.vpy NUL
vspipe: symbol lookup error: /usr/lib64/vapoursynth/libknlmeanscl.so: undefined symbol: GOMP_parallel

**Comment by 4re** [comment]
It works fine here, are you using one of the latest versions for knlmenascl from the overlay?
Try to reinstall them and try again please.
Also the vspipe line should be ```vspipe -p cl.vpy /dev/null``` that line creates a file on Linux.

**Comment by brothermechanic** [comment]
Yes! Works!
Test with this script https://bpaste.net/show/dfa4a8ebf33c
http://wstaw.org/m/2015/09/08/plasma-desktopXg4436.png
ON GPU!!!
device_id=0 - cpu, device_id=1 - first gpu, device_id=2 - secong gpu? right?
But dont work vspipe
$ vspipe -p cl.vpy /dev/null
vspipe: symbol lookup error: /usr/lib64/vapoursynth/libknlmeanscl.so: undefined symbol: GOMP_parallel

and it's dont work with script https://bpaste.net/show/dfa4a8ebf33c
vspipe --y4m KNLMeansCL.vpy - | ffplay -i pipe:
http://wstaw.org/m/2015/09/08/plasma-desktopal4436.png (test on cpu, gpu)
Thank you! Anyway this is great software!

**Comment by Khanattila** [comment]
@brothermechanic I fixed it in the v0.6.3 release. It was a problem of localization with floating number.

**Comment by 4re** [comment]
@brothermechanic the good news for you is that everything is working, wen you use vspipe to pass the video to an encoder or a video player you need to convert the video data from float to integer first for it to display correctly (vsedit does this automatically).
Add ```clp = core.fmtc.bitdepth(clp, bits=10, fulls=True, flt=False)``` just before ```clp.set_output ()``` and you are done. :)

**Comment by brothermechanic** [comment]
Thank you!
Now it works like a charm!

**Comment by brothermechanic** [comment]
This is my test https://dl.dropboxusercontent.com/u/34973756/distfiles/KNLMeansCL.mp4
script https://bpaste.net/show/d58ba8761cf6
