### ISSUE TITLE
Image border artifacts

### ISSUE THREAD

**Issue by brothermechanic** [Khanattila/KNLMeansCL#7]
Hello
I have some issue with KNLMeansCL filter
Please look at this video https://dl.dropboxusercontent.com/u/34973756/distfiles/camera1-filter-02.mp4
There are an artifacts on borders like image stringiness.
I filtered it with tis script https://dl.dropboxusercontent.com/u/34973756/distfiles/camera1-02.vpy
This is a bug? or i use KNLMeansCL with wrong options?
Please help.

**Comment by Khanattila** [comment]
Take a pixel on the left border, example p = (0, 640) .
This pixel should be used as reference all the pixels comprised between (0-24, 640-24) and (0+24, 640+24). But pixel with negative x do not exist! So KNLMeansCL use a pixel on the edge instead.

A possible solution is to use a smaller 'a' and bigger 'd', like "d=1, a=9" or "d=2, a=7".
