### ISSUE TITLE
Does not compile with GCC

### ISSUE THREAD

**Issue by 4re** [Khanattila/KNLMeansCL#8]
I got this errors http://pastebin.com/YCU3dJBJ with latest git.

**Comment by Khanattila** [comment]
As you can see G ++ runs. https://travis-ci.org/Khanattila/KNLMeansCL

"warning: pkg-config or pc files not found, lib detection may be inaccurate."
It seems like some libs are missing.

**Comment by 4re** [comment]
OK, I did some more research, 15e09913dc949db8baa5f9ca8c35c4b55b853f42 is the offending commit, so it looks like nvidia's cuda toolkit does not support opencl 1.2, lovely.

Fortunately if one switches to mesa opencl for the build and then switches back to nvidia everything works great.

**Comment by Khanattila** [comment]
Header are provided buy http://khronos.org/. 
You can also use the package opencl-headers.
 http://packages.ubuntu.com/search?keywords=opencl-headers

**Comment by 4re** [comment]
I'm on a Gentoo, not Ubuntu, and the problem was with the package to build this plugin, because if one uses Nvidia the system wide set opencl implementation you need to run the plug-in differs from the one you need to build it.

But I will figure it out how to do it automated so users don't have to bother with it. Thx anyway.

**Comment by 4re** [comment]
And thx for your great plug-in, it's really awesome. ^__^
