### ISSUE TITLE
Confiugre on Mac

### ISSUE THREAD

**Issue by invisiblearts** [Khanattila/KNLMeansCL#9]
The original configure failed on Mac. Should be revised.
1. While checking OpenCL, should include `<OpenCL/cl.h>` on Mac.
2. Should link against OpenCL framework( -framework opencl) instead of -lopencl. A quick and dirty fix is to let CXX=clang++ -framework opencl

**Comment by Khanattila** [comment]
Simply configure does not support mac os x

**Comment by Khanattila** [comment]
Try with last commit.

**Comment by invisiblearts** [comment]
Still, OpenCL checking failed because on Mac should include `<OpenCL/cl.h>`. Apple's fault... Everything works fine except that.

**Comment by Khanattila** [comment]
Fixed.
